### ISSUE TITLE
'PEVideos_JAXBElement<string>.h' file not found

### ISSUE THREAD

**Issue by saru2020** [bulldog2011/pico#2]
Can anyone help me with this error:
"'PEVideos_JAXBElement< string >.h' file not found"

There is no "'PEVideos_JAXBElement< string >.h" file generated from wsdl conversion.
Also, the <> arrow parenthesis near the class name seems weird.
I haven't seen names such like that.

Please help!!!

Thx!
Saravanan

**Comment by bulldog2011** [comment]
Can you share your wsdl/schema with me, so I may verify on my machine to identify the root cause.

My mail box: 51startup@sina.com

Thx!
-William

**Comment by bulldog2011** [comment]
Hi,

The root cause of this issue is your wsdl is not following jaxb convension, see details here:
http://docs.oracle.com/cd/E19879-01/820-1072/ahiid/index.html
http://stackoverflow.com/questions/12508741/jaxb-generating-jaxbelementstring-instead-of-string

Please create a custom binding file(for example binding.xjb) with following content:
`
<jaxb:bindings version="2.0"
               xmlns:jaxb="http://java.sun.com/xml/ns/jaxb">
    <jaxb:bindings>
        <jaxb:globalBindings generateElementProperty="false"/>
    </jaxb:bindings>
</jaxb:bindings>
`

Then generate code with custom binding option specified:
bin/mwsc -pico -prefix PEVideo_ -d generated -b binding.xjb http://your.wsdl

Please try and let me know if this work for you.

Thx!
-William

**Comment by saru2020** [comment]
Thanks that works fine for me!!!
